#!/bin/bash -x
echo "Enter a number"
read num1
echo "Enter another number"
read num2
echo "The total of the two entered number is" $(($num1 + $num2))

if [ $num1 -gt $num2 ]; then
        echo "The first number - $num1 is greater than the second number - $num2"
elif [ $num1 -eq $num2 ]; then
        echo "The first number $num1 and second number $num2 are equali"
else echo "The second number - $num2 is greater than the first number - $num1"
fi
